name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.16
		
    - name: run
      run: |
        python YG_house_numbers.py
		
    - name: commit
      run: |
        git config --global user.email lailongzhou@yeah.net
        git config --global user.name rylynnlai
        git add .
        git commit -m "update" -a
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
